version: "2"

formatters:
  enable:
    - gofumpt
    - goimports

linters:
  enable:
    - asciicheck
    - bidichk
    - dupword
    - durationcheck
    - errcheck
    - errorlint
    - gocritic
    - godox
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nolintlint
    - prealloc
    - predeclared
    - staticcheck
    - tagalign
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl_v5
